deployed fully correct ! at sep10, all are correct adn trying to apply on linkedIn

diff --git a/back/Dockerfile.prod b/back/Dockerfile.prod
--- a/back/Dockerfile.prod
+++ b/back/Dockerfile.prod
@@ -1,24 +1,48 @@
+# FROM node:24-alpine AS builder
+# WORKDIR /app
+# COPY package*.json ./
+# RUN npm ci --legacy-peer-deps
+# COPY . .
+# RUN npm run build
+
+# FROM node:24-alpine AS production
+# WORKDIR /app
+# COPY --from=builder /app/package*.json ./
+# COPY --from=builder /app/node_modules ./node_modules
+# COPY --from=builder /app/dist ./dist
+# COPY --from=builder /app/tsconfig.json ./
+# COPY --from=builder /app/uploads/default-avatar.png ./uploads/
+
+# RUN addgroup -g 1001 -S nodejs && adduser -S nodejs -u 1001
+# RUN chown -R nodejs:nodejs /app
+# USER nodejs
+
+# EXPOSE 3001
+# HEALTHCHECK --interval=30s --timeout=10s --start-period=30s --retries=3 \
+#   CMD wget --no-verbose --tries=1 --spider http://localhost:3001/health || exit 1
+
+# CMD ["node", "-r", "module-alias/register", "dist/main.js"]
+
 FROM node:24-alpine AS builder
 WORKDIR /app
 COPY package*.json ./
-RUN npm ci --legacy-peer-deps
+RUN npm install   --legacy-peer-deps
 COPY . .
 RUN npm run build
 
 FROM node:24-alpine AS production
 WORKDIR /app
 COPY --from=builder /app/package*.json ./
-COPY --from=builder /app/node_modules ./node_modules
+RUN npm install --omit=dev --legacy-peer-deps --only=production  
 COPY --from=builder /app/dist ./dist
-COPY --from=builder /app/tsconfig.json ./
+# COPY --from=builder /app/public ./public
 COPY --from=builder /app/uploads/default-avatar.png ./uploads/
 
 RUN addgroup -g 1001 -S nodejs && adduser -S nodejs -u 1001
-RUN chown -R nodejs:nodejs /app
 USER nodejs
 
 EXPOSE 3001
 HEALTHCHECK --interval=30s --timeout=10s --start-period=30s --retries=3 \
-  CMD wget --no-verbose --tries=1 --spider http://localhost:3001/health || exit 1
+  CMD wget --no-verbose --tries=1 --spider http://127.0.0.1:3001/api/health || exit 1
 
 CMD ["node", "-r", "module-alias/register", "dist/main.js"]
